clone_depth: 1
image:
- Visual Studio 2015
environment:
  matrix:
    - mingw_bin: 'C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin'
    - mingw_bin: 'C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin'
install:
  - set PATH=%mingw_bin%;%PATH%
build_script:
  - echo %PATH% 
  - cmake -G "MSYS Makefiles" -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin" . && mingw32-make
test_script:
- mingw32-make

